name: easy_linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 1.0.3
homepage: https://github.com/imsujan276/easy_linkedin_login
repository: https://github.com/imsujan276/easy_linkedin_login

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.9.1
  rxdart: ^0.27.7
  uuid: ^4.0.0
  webview_flutter: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.3

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
